package userinterface.CreateOrganization;

import javax.swing.JOptionPane;
import model.StoreMgmtSystem;

/**
 *
 * @author saidutt
 */
public class NewOrganizationJPanel extends javax.swing.JPanel {

    private StoreMgmtSystem system;
    /**
     * Creates new form NewOrganizationJPanel
     */
    public NewOrganizationJPanel(StoreMgmtSystem pSystem) {
        initComponents();
        
        populateOrgTypes();        
        this.system = pSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        comboOrgType = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Organization");

        comboOrgType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        comboOrgType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrgTypeActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel5.setText("Organization type");

        jLabel2.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fldName)
                    .addComponent(comboOrgType, 0, 146, Short.MAX_VALUE))
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboOrgType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(0, 431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateOrgTypes() {
        
        this.comboOrgType.addItem("Inventory Distributor");
        this.comboOrgType.addItem("Inventory Manufacturer");
        this.comboOrgType.addItem("Inventory Transporter");
        this.comboOrgType.addItem("Local Store");
        this.comboOrgType.addItem("Online store");
        this.comboOrgType.addItem("Taxation");
    }
    
    private void comboOrgTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrgTypeActionPerformed

        
        
    }//GEN-LAST:event_comboOrgTypeActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (this.fldName.getText().equals("") || ((String)this.comboOrgType.getSelectedItem()).equals("Select")) {
            
            JOptionPane.showMessageDialog(null, "Enter valid organization type");
           
        } else if (this.fldName.getText().equals("Inventory Distributor")) {
            
            this.system.getInventoryEnterprise().newInvDistributorOrganization(this.fldName.getText());
            
        } else if (this.fldName.getText().equals("Inventory Manufacturer")) {
            
            this.system.getInventoryEnterprise().newInvManufacturerOrganization(this.fldName.getText());
            
        } else if (this.fldName.getText().equals("Inventory Transporter")) {
            
            this.system.getInventoryEnterprise().newInvTransportationOrganization(this.fldName.getText());
            
        } else if (this.fldName.getText().equals("Local Store")) {
            
            this.system.getStoreEnterprise().newLocalStoreOrganization(this.fldName.getText());
            
        } else if (this.fldName.getText().equals("Online store")) {
            
            this.system.getCustomerEnterprise().newOnlineStoreOrganization(this.fldName.getText());
            
        } else {
            
            this.system.getComplianceEnterprise().newTaxationOrganization(this.fldName.getText());
        }         
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboOrgType;
    private javax.swing.JTextField fldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
