package userinterface.RolesWorkArea;

import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import model.Organization.InvDistributorOrganization;
import model.Organization.InvManufacturerOrganization;
import model.Organization.InvTransportationOrganization;
import model.Organization.LocalStoreOrganization;
import model.Organization.OnlineStoreOrganization;
import model.Organization.TaxationOrganization;
import model.StoreMgmtSystem;
import model.UserAccount.UserAccount;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author saidutt
 */
public class TaxAuditorJPanel extends javax.swing.JPanel {

    private   UserAccount user;
    /**
     * Creates new form TaxAuditorJPanel
     * @param pUser
     */
    public TaxAuditorJPanel(UserAccount pUser) {
        
        initComponents();
        this.user = pUser;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPane3 = new javax.swing.JTabbedPane();
        paneWelcome3 = new javax.swing.JPanel();
        lblWelcome5 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblDispName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblDispRole = new javax.swing.JLabel();
        paneOrganizations = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAudit = new javax.swing.JTable();
        btnChart = new javax.swing.JButton();

        tbdPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbdPane3StateChanged(evt);
            }
        });

        lblWelcome5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblWelcome5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome5.setText("Welcome");
        lblWelcome5.setName(""); // NOI18N

        lblUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Name - ");

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Role - ");

        javax.swing.GroupLayout paneWelcome3Layout = new javax.swing.GroupLayout(paneWelcome3);
        paneWelcome3.setLayout(paneWelcome3Layout);
        paneWelcome3Layout.setHorizontalGroup(
            paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWelcome3Layout.createSequentialGroup()
                .addGroup(paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneWelcome3Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(lblWelcome5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneWelcome3Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDispName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDispRole, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        paneWelcome3Layout.setVerticalGroup(
            paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWelcome3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblWelcome5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDispName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneWelcome3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDispRole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        tbdPane3.addTab("Welcome", paneWelcome3);

        tblAudit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Organization type", "Total revenue", "Tax amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAudit);

        btnChart.setText("Show chart");
        btnChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneOrganizationsLayout = new javax.swing.GroupLayout(paneOrganizations);
        paneOrganizations.setLayout(paneOrganizationsLayout);
        paneOrganizationsLayout.setHorizontalGroup(
            paneOrganizationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(paneOrganizationsLayout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneOrganizationsLayout.setVerticalGroup(
            paneOrganizationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOrganizationsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbdPane3.addTab("Organizations", paneOrganizations);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbdPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbdPane3StateChanged

        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();

        switch(index) {

            case 1 : populateAuditTable();
            break;            
        }
    }//GEN-LAST:event_tbdPane3StateChanged

    private void btnChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartActionPerformed
        
        // Create dataset
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        DefaultTableModel model = (DefaultTableModel) tblAudit.getModel();
        
        for (int row=0; row < model.getRowCount(); row++) {
            
            dataset.addValue((Float)model.getValueAt(row, 3), "Sales", (String)model.getValueAt(row, 1));
        }                        

        // Create the chart
        JFreeChart chart = ChartFactory.createBarChart(
                "Tax amount", // Chart title
                "Organization", // Domain axis label
                "Tax amount (in USD)", // Range axis label
                dataset // Dataset
        );

        
        ChartFrame frame = new ChartFrame("Bar Chart Example", chart);
        frame.pack();
        frame.setVisible(true);
        
    }//GEN-LAST:event_btnChartActionPerformed

    
    private void populateAuditTable () {
        
        StoreMgmtSystem system = ((TaxationOrganization)this.user.getParentOrg()).getComplianceEnterprise().getSystem();
        DefaultTableModel model = (DefaultTableModel) tblAudit.getModel();
        model.setRowCount(0);
        
        for (OnlineStoreOrganization oso : system.getCustomerEnterprise().getOnlineStrOrgList()) {
            
            model.addRow(new Object[] {oso.getName(), "Online store organization", oso.getTotalRevenue(), oso.getTotalTaxAmount()});            
        }
        
        for (LocalStoreOrganization lso : system.getStoreEnterprise().getLocalOrgList()) {
            
            model.addRow(new Object[] {lso.getName(), "Local store organization", lso.getTotalRevenue(), lso.getTotalTaxAmount()});            
        }
        
        for (InvManufacturerOrganization imo : system.getInventoryEnterprise().getInvManOrgList()) {
            
            model.addRow(new Object[] {imo.getName(), "Inv Man Organization", imo.getTotalRevenue(), imo.getTotalTaxAmount()});
        }
        
        for (InvDistributorOrganization ido : system.getInventoryEnterprise().getInvDisOrgList()) {
            
            model.addRow(new Object[] {ido.getName(), "Inv Dis Organization", ido.getTotalRevenue(), ido.getTotalTaxAmount()});        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDispName;
    private javax.swing.JLabel lblDispRole;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome5;
    private javax.swing.JPanel paneOrganizations;
    private javax.swing.JPanel paneWelcome3;
    private javax.swing.JTabbedPane tbdPane3;
    private javax.swing.JTable tblAudit;
    // End of variables declaration//GEN-END:variables
}
